package events

// Alert extends a base Event with detection-specific metadata.
// Alerts are generated by detection engines when a threat or suspicious activity is identified.
type Alert struct {
	Event

	// RuleName is the name of the detection rule that triggered this alert.
	RuleName string `json:"rule.name"`

	// RuleID is the unique identifier of the detection rule.
	RuleID string `json:"rule.id"`

	// RuleDescription provides a human-readable description of what was detected.
	RuleDescription string `json:"rule.description"`

	// Action taken (if any): "alert", "block", "quarantine", "kill"
	Action string `json:"event.action"`

	// Risk score 0-100
	RiskScore int `json:"event.risk_score"`

	// References to related events (e.g., the process event that triggered the alert)
	RelatedEvents []string `json:"related.events,omitempty"`
}
