#!/usr/bin/env bash
# xdr-agent - Modular XDR endpoint security agent for Linux
# Copyright (C) 2026  Diego A. Guillen-Rosaperez
# SPDX-License-Identifier: AGPL-3.0
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop xdr-agent.service || true
  systemctl disable xdr-agent.service || true
fi

exit 0
